### 搜索课程
GET {{search_host}}/search/course/list?pageNo=1&pageSize=10&keywords=
Content-Type: application/json

### 添加课程索引
POST {{search_host}}/search/index/course
Content-Type: application/json

{
  "charge" : "201001",
  "companyId" : 1232141425,
  "companyName" : null,
  "createDate" : null,
  "description" : "冻坏的花朵哈迪哦按段饿哦爱好的哈迪好饿啊大号哈佛啊好哈就奥",
  "grade" : "204002",
  "id" : 206,
  "mt" : "1-8",
  "mtName" : "游戏开发",
  "name" : "Es从0到无",
  "originalPrice" : null,
  "pic" : "/mediafiles/2024/09/27/584ddd95ac937f21bd1c0ef22fc2896e.jpg",
  "price" : null,
  "remark" : null,
  "st" : "1-8-3",
  "stName" : "Flash",
  "status" : "203002",
  "tags" : "牛马程序员",
  "teachmode" : "200002",
  "validDays" : 365
}